server:
    port: 8888
spring:
    application:
        name: AnimalSystem
    datasource:
        username: root
        password: Ylp050413
        url: jdbc:mysql://127.0.0.1:3306/animal?userUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: HTML5
        suffix: .html
        prefix: classpath:/templates/

mybatis:
    type-aliases-package: com.bnu.pojo
    mapper-locations: classpath*:/mapper/*.xml #加载此路径下的映射文件
    configuration:

        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true #自动分页
    params: count=countsql